### ISSUE TITLE
CPU, RAM, and GPU processes not showing

### ISSUE THREAD

**Issue by gillyw33d** [Jax-Core/Plainext#12]
As title says, the CPU, RAM, and GPU measures aren't showing the processes using them
[Plainext.zip](https://github.com/Jax-Core/Plainext/files/8065637/Plainext.zip)

**Comment by gillyw33d** [comment]
Updated and it's fixed now

**Comment by giquo** [comment]
Hi, Sorry
I just installed JaxCore and I liked plaintext but I just see the percentage of use, I don't see any process list, what did I miss?
sorry to ask if the answer is right in front of me

**Comment by giquo** [comment]
Ah ok, now I see the issue
1. when I change the skin scale, the processes got lost
2. when I change to RIGHT position, some data gets lost
