### ISSUE TITLE
Installer can't be moved, takes focus

### ISSUE THREAD

**Issue by cfjedimaster** [Jax-Core/Plainext#14]
While running the installer, I had to switch to something else, and noticed you can't move the installer nor can you put anything else on top of it.

**Comment by EnhancedJax** [comment]
Get plainext from JaxCore. https://JaxCore.app

**Comment by cfjedimaster** [comment]
I did. :)

**Comment by EnhancedJax** [comment]
You're talking about the welcome screen? Just go through it lol

**Comment by cfjedimaster** [comment]
Um, sure, it isn't the end of the world, but it is unusual for an installer. If you don't care that's fine, but I figured I'd report it. Feel free to close I suppose. The widget works great, thank you for making it.
